// flow-typed signature: 3cbd0d4cb6602edfd455342010592b19
// flow-typed version: <<STUB>>/react-native-material-design_v^0.3.7/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-material-design'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-material-design' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-material-design/lib/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Button' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Card/Actions' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Card/Body' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Card/index' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Card/Media' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Checkbox' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/CheckboxGroup' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/config' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Divider' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Drawer/Header' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Drawer/index' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Drawer/Section' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Icon' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/IconToggle' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/List' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/polyfill/Elevation' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/polyfill/Ripple' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/RadioButton' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/RadioButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Ripple' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Subheader' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/Toolbar' {
  declare module.exports: any;
}

declare module 'react-native-material-design/lib/VectorIconComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-material-design/lib/Avatar.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Avatar'>;
}
declare module 'react-native-material-design/lib/Button.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Button'>;
}
declare module 'react-native-material-design/lib/Card/Actions.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Card/Actions'>;
}
declare module 'react-native-material-design/lib/Card/Body.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Card/Body'>;
}
declare module 'react-native-material-design/lib/Card/index.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Card/index'>;
}
declare module 'react-native-material-design/lib/Card/Media.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Card/Media'>;
}
declare module 'react-native-material-design/lib/Checkbox.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Checkbox'>;
}
declare module 'react-native-material-design/lib/CheckboxGroup.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/CheckboxGroup'>;
}
declare module 'react-native-material-design/lib/config.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/config'>;
}
declare module 'react-native-material-design/lib/Divider.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Divider'>;
}
declare module 'react-native-material-design/lib/Drawer/Header.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Drawer/Header'>;
}
declare module 'react-native-material-design/lib/Drawer/index.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Drawer/index'>;
}
declare module 'react-native-material-design/lib/Drawer/Section.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Drawer/Section'>;
}
declare module 'react-native-material-design/lib/helpers.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/helpers'>;
}
declare module 'react-native-material-design/lib/Icon.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Icon'>;
}
declare module 'react-native-material-design/lib/IconToggle.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/IconToggle'>;
}
declare module 'react-native-material-design/lib/index.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/index'>;
}
declare module 'react-native-material-design/lib/List.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/List'>;
}
declare module 'react-native-material-design/lib/polyfill/Elevation.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/polyfill/Elevation'>;
}
declare module 'react-native-material-design/lib/polyfill/Ripple.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/polyfill/Ripple'>;
}
declare module 'react-native-material-design/lib/RadioButton.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/RadioButton'>;
}
declare module 'react-native-material-design/lib/RadioButtonGroup.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/RadioButtonGroup'>;
}
declare module 'react-native-material-design/lib/Ripple.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Ripple'>;
}
declare module 'react-native-material-design/lib/Subheader.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Subheader'>;
}
declare module 'react-native-material-design/lib/Toolbar.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/Toolbar'>;
}
declare module 'react-native-material-design/lib/VectorIconComponent.js' {
  declare module.exports: $Exports<'react-native-material-design/lib/VectorIconComponent'>;
}
