# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appZone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appZone

  pod 'GoogleMaps', '2.1.1'

  # React stuff
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Fonts
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'appZoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
